## Annetaan tietueille nimet
## alkuperäinen data oli CSV-muotoinen ehdokaskohtainen kuntavaalitulos täältä:
## http://tulospalvelu.vaalit.fi/KV-2017/fi/ladattavat_tiedostot.html
## Tiedosto on liian iso githubille, joten jätän sen pois.
library(tidyverse)

nms <- cols(
    X1 = col_character(),
    X2 = col_character(),
    X3 = col_character(),
    X4 = col_character(),
    X5 = col_character(),
    X6 = col_character(),
    X7 = col_character(),
    X8 = col_character(),
    X9 = col_character(),
    X10 = col_integer(),
    X11 = col_integer(),
    X12 = col_character(),
    X13 = col_character(),
    X14 = col_character(),
    X15 = col_integer(),
    X16 = col_character(),
    X17 = col_character(),
    X18 = col_character(),
    X19 = col_character(),
    X20 = col_factor(1:2),
    X21 = col_integer(),
    X22 = col_character(),
    X23 = col_character(),
    X24 = col_character(),
    X25 = col_character(),
    X26 = col_character(),
    X27 = col_integer(),
    X28 = col_integer(),
    X29 = col_integer(),
    X30 = col_integer(),
    X31 = col_character(),
    X32 = col_integer(),
    X33 = col_integer(),
    X34 = col_integer(),
    X35 = col_integer(),
    X36 = col_double(),
    X37 = col_double(),
    X38 = col_double(),
    X39 = col_integer(),
    X40 = col_double(),
    X41 = col_integer(),
    X42 = col_double(),
    X43 = col_character(),
    X44 = col_character(),
    X45 = col_character(),
    X46 = col_character()
)

kunta <- read_delim("../data/kuntavaalit.csv",
                    delim = ";",
                    col_names = FALSE,
                    col_types = nms,
                    trim_ws = TRUE,
                    quote="'")

kunta <- kunta[-46]

names(kunta) <- c("Vaalilaji",
                  "Vaalipiirinumero",
                  "Kuntanumero",
                  "Tietuetyyppi",
                  "Äänestysaluetunnus",
                  "Vaalipiirin lyhenne suomeksi",
                  "Vaalipiirin lyhenne ruotsiksi",
                  "Pysyvä puoluetunniste",
                  "Vakiopuoluenumero",
                  "Listajärjestysnumero",
                  "Vaaliliittonumero",
                  "Puolueen/ryhmän nimilyhenne suomeksi",
                  "Puolueen/ryhmän nimilyhenne ruotsiksi",
                  "Puolueen/ryhmän nimilyhenne englanniksi",
                  "Ehdokasnumero",
                  "Kunnan/vaalipiirin/äänestysalueen nimi suomeksi",
                  "Kunnan/vaalipiirin/äänestysalueen nimi ruotsiksi",
                  "Henkilön etunimi",
                  "Henkilön sukunimi",
                  "Sukupuoli",
                  "Ikä vaalipäivänä",
                  "Ammatti",
                  "Kotikunnan koodi",
                  "Kotikunnan nimi suomeksi",
                  "Kotikunnan nimi ruotsiksi",
                  "Ehdokkaan äidinkieli",
                  "Europarlamentaarikko",
                  "Kansanedustaja",
                  "Kunnanvaltuutettu",
                  "Maakuntavaltuutettu",
                  "Vaalitapahtuman nimilyhenne 1. vertailuvaali",
                  "Ääniä 1. vertailuvaali",
                  "Ennakkoäänet lkm",
                  "Vaalipäivän äänet lkm",
                  "Äänet yhteensä lkm",
                  "Osuus ennakkoäänistä ",
                  "Osuus vaalipäivän äänistä (%)",
                  "Osuus äänistä yhteensä ",
                  "Valintatieto",
                  "Vertausluku",
                  "Sija",
                  "Lopullinen sija",
                  "Laskennan tila",
                  "Laskentavaihe",
                  "Viimeisin päivitys")

unique(kunta$Äänestysaluetunnus)
kunta <- kunta %>% select(1:6,8,11,12,15,16,18:24,26,27:29,33:40,42)

write_csv(kunta, "../results/kuntavaalit_siisti.csv")
